alias gullos="git pull origin staging"
alias gullom="git pull origin master"
alias gushos="git push origin staging"
alias gushom="git push origin master"
alias gibra="git branch"
alias gista="git status"
alias gchs="git checkout staging"
alias gchm="git checkout master"
alias gadd="git add"
alias gommit="git commit -m"

